### ISSUE TITLE
Plugin not loading on velocity

### ISSUE THREAD

**Issue by KickSquareMC** [4drian3d/TitleAnnouncer#16]
Hey, I've installed the plugin on velocity 3.0.1 & java 16, and it's not loading. It gives the following error on startup:

```[21:25:37 ERROR]: Can't create plugin titleannouncer
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInjectingConstructor]: NoSuchMethodError: 'Component Component.compact()'
  at Announcer.<init>(Announcer.java:36)
  at VelocityPluginModule.configure(VelocityPluginModule.java:48)
  while locating Announcer

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
Announcer:            "net.dreamerzero.titleannouncer.velocity.Announcer"
Component:            "net.kyori.adventure.text.Component"
VelocityPluginModule: "com.velocitypowered.proxy.plugin.loader.java.VelocityPluginModule"
========================
End of classname legend:
========================

        at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251) ~[server.jar:3.0.1]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1103) ~[server.jar:3.0.1]
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1138) ~[server.jar:3.0.1]
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:121) ~[server.jar:3.0.1]
        at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:152) ~[server.jar:3.0.1]
        at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:325) ~[server.jar:3.0.1]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:223) ~[server.jar:3.0.1]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:64) ~[server.jar:3.0.1]
Caused by: java.lang.NoSuchMethodError: 'net.kyori.adventure.text.Component net.kyori.adventure.text.Component.compact()'
        at net.dreamerzero.titleannouncer.libs.net.kyori.adventure.text.minimessage.MiniMessageImpl.<clinit>(MiniMessageImpl.java:45) ~[?:?]
        at net.dreamerzero.titleannouncer.libs.net.kyori.adventure.text.minimessage.MiniMessage.miniMessage(MiniMessage.java:70) ~[?:?]
        at net.dreamerzero.titleannouncer.velocity.Announcer.<init>(Announcer.java:38) ~[?:?]
        at net.dreamerzero.titleannouncer.velocity.Announcer$$FastClassByGuice$$5040791.GUICE$TRAMPOLINE(<generated>) ~[?:?]
        at net.dreamerzero.titleannouncer.velocity.Announcer$$FastClassByGuice$$5040791.apply(<generated>) ~[?:?]
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[server.jar:3.0.1]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[server.jar:3.0.1]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[server.jar:3.0.1]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296) ~[server.jar:3.0.1]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[server.jar:3.0.1]
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[server.jar:3.0.1]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[server.jar:3.0.1]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1100) ~[server.jar:3.0.1]
        ... 6 more
```

**Comment by 4drian3d** [comment]
Hi, the latest version of TitleAnnouncer only works with the latest development versions of Velocity which can be found at https://versions.velocitypowered.com/download/3.0.x-SNAPSHOT.jar

In case you want to continue using the plugin in Velocity 3.0.1, you can use an older version of TitleAnnouncer.

**Comment by KickSquareMC** [comment]
Thanks for the reply! Which version should I use for 3.0.1?

**Comment by 4drian3d** [comment]
I don't know exactly in which version this change was introduced (GitHub doesn't want to show it apparently). I would recommend you to upgrade to the latest development version of Velocity, it is quite stable and you will not have problems with any plugin.

**Comment by 4drian3d** [comment]
Velocity 3.1.0 is now available at https://velocitypowered.com/downloads
